using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;

namespace _2
{

    /*
     * 
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     * 
     */

    class Program
    {
        static void Main(string[] args)
        {
            var sw = new Stopwatch();
            sw.Start();

            var G = new Program();
            var sum = 0;
            var fibonacciSequence = G.etFibonacci(4000000);

            foreach (var value in fibonacciSequence.Where(v => v % 2 == 0))
            {
                sum += value;
            }

            sw.Stop();
            var time = sw.ElapsedMilliseconds;

            Console.WriteLine("The answer is {0} and it took {1} milliseconds", sum, time);
        }

        public List<int> etFibonacci(int max)
        {
            var fibo = new List<int>();
            var first = 0;
            var second = 1;
            var value = second;

            fibo.Add(first);
            fibo.Add(second);

            var previousPreviousValue = first;
            var previousValue = second;

            while (value <= max)
            {
                var newFibo = previousValue + previousPreviousValue;

                fibo.Add(newFibo);

                previousPreviousValue = previousValue;
                previousValue = newFibo;
                value = newFibo;
            }
            return fibo;
        }
    }
}
