# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and 
# D = |Pk − Pj| is minimised; what is the value of D?

require 'mathn'
require 'set'

start = Time.now

max_pent = 3000
pent_numbers = (1..max_pent).map {|n| n*(3*n - 1) / 2}.to_set

answer = pent_numbers.to_a.combination(2).select {|a,b| 
  pent_numbers.include?(a+b) && pent_numbers.include?(b-a)
}.map {|a,b| b-a}.min

puts "The answer is #{answer} and it took #{Time.now - start} seconds."